definitions:
  patientcommands.CreatePatientProfileCmdDTO:
    properties:
      address:
        type: string
      city:
        type: string
      district:
        type: string
      dob:
        type: string
      email:
        type: string
      full-name:
        type: string
      password:
        type: string
      phone-number:
        type: string
      ward:
        type: string
    type: object
  relativescommands.CreateRelativeAccountCmdDTO:
    properties:
      address:
        type: string
      city:
        type: string
      district:
        type: string
      dob:
        type: string
      email:
        type: string
      full-name:
        type: string
      password:
        type: string
      phone-number:
        type: string
      ward:
        type: string
    type: object
info:
  contact: {}
  title: Patient Service
  version: "1.0"
paths:
  /api/v1/patients:
    post:
      consumes:
      - application/json
      description: create patient profile
      parameters:
      - description: account creation data
        in: body
        name: form
        required: true
        schema:
          $ref: '#/definitions/patientcommands.CreatePatientProfileCmdDTO'
      produces:
      - application/json
      responses:
        "200":
          description: data
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad request error
          schema: {}
      summary: create patient profile
      tags:
      - patient
  /api/v1/relatives:
    post:
      consumes:
      - application/json
      description: create relatives account
      parameters:
      - description: account creation data
        in: body
        name: form
        required: true
        schema:
          $ref: '#/definitions/relativescommands.CreateRelativeAccountCmdDTO'
      produces:
      - application/json
      responses:
        "200":
          description: data
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad request error
          schema: {}
      summary: create relatives account
      tags:
      - relative
  /ping:
    get:
      consumes:
      - application/json
      description: ping server
      produces:
      - application/json
      responses:
        "200":
          description: message success
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad request error
          schema: {}
      summary: ping server
      tags:
      - ping
swagger: "2.0"
